language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - WP_VERSION=master WP_MULTISITE=0
    - WP_VERSION=3.6.1 WP_MULTISITE=0
    - WP_VERSION=3.6 WP_MULTISITE=0
    - WP_VERSION=3.5.2 WP_MULTISITE=0
    - WP_VERSION=3.5.1 WP_MULTISITE=0
    - WP_VERSION=3.5 WP_MULTISITE=0
    - WP_VERSION=master WP_MULTISITE=1
    - WP_VERSION=3.6.1 WP_MULTISITE=1
    - WP_VERSION=3.6 WP_MULTISITE=1
    - WP_VERSION=3.5.2 WP_MULTISITE=1
    - WP_VERSION=3.5.1 WP_MULTISITE=1
    - WP_VERSION=3.5 WP_MULTISITE=1

before_script:
    - wget https://raw.github.com/tierra/wordpress-plugin-tests/setup/setup.sh
    - source setup.sh

script:
    - phpunit
    #- php tests/includes/clover.php tests/clover.xml 90

notifications:
    email:
        recipients:
          - ghost1227@reduxframework.com
          - dovy@reduxframework.com
        on_success: change
        on_failure: always

# wordpress-plugin-tests specific config
# Tells Travis CI not to run unit tests against the setup branch
branches:
    except:
        - setup